### PR TITLE
Added Py3.{5,6} & Django 1.11. Removed Py2.6 & Django <1.8

### PR DESCRIPTION
**Pull request by alanjds**
The latest Django LTS is 1.11. Its ok to support up to the "LTS -1" (1.8) only.
The next Django LTS is 2.0, and will be Py3k only, so lets start testing with Py3k!

### CODE REVIEW

**Comment by phpdude** [comment]
Hi Alan,

Looks good to me. So it works with Django 2.0 & python 3.{5,6}? Because in the PR I see only tests configuration fixes, not source code fixes.

**Comment by alanjds** [comment]
Yeah, it works! I was expecting to need to fix stuff, but no alarm raised. Nice, right?

**Comment by phpdude** [comment]
Yep! That's awesome :-)

I will try to check the tests today later and will approve it. At the moment I am still out of home.

**Comment by phpdude** [comment]
@alanjds I am sorry, I forgot about the fixes. Merged and now I am testing it all.

**Comment by phpdude** [comment]
@alanjds updated https://pypi.python.org/pypi/django-macros-url/0.4.0 :-)

**Pull request merged**
